name: "Run Newman Tests"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman + HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Run API tests with HTML report
        run: |
          newman run "Restful Booker BVT.postman_collection.json" \
          -e "Production.postman_environment.json_
